//This is a .dbml file to visualize the database. It uses the dbdiagram.io official vscode extension for highlight, suggestion and the visualisation using the open preview icon on the line with the split editor icon

Enum User_roles{
    reader
    author
    admin
}

Table Users {
    id int [primary key, increment]
    name varchar(15) [not null]
    email varchar(20) [unique, not null]
    email_verified_at date
    password varchar(255) [not null]
    role User_roles [default: User_roles.reader]
    created_at datetime
    updated_at datetime
}

Enum Articles_statuses{
    craft
    published
    archived
}

Table Articles {
    id int [primary key, increment]
    user_id int [ref: > Users.id]
    title varchar(30) [not null]
    content text [not null]
    status Articles_statuses [default: Articles_statuses.craft]
    created_at datetime
    updated_at datetime
}

Table Comments {
    id int [primary key, increment]
    article_id int [ref: > Articles.id]
    content text [not null]
}

Table Categories{
    id int [primary key, increment]
}
